from .Badge import Badge as BadgeDBModel
from .BadgeCondition import BadgeCondition as BadgeConditionDBModel
from .BadgeType import BadgeType as BadgeTypeDBModel
from .Organization import Organization as OrganizationDBModel
from .OrganizationType import OrganizationType as OrganizationTypeDBModel
from .OrgPos import OrgPos as OrgPosDBModel
from .People import People as PeopleDBModel
from .PeopleCredential import PeopleCredential as PeopleCredentialDBModel
from .PeoplePosRole import PeoplePosRole as PeoplePosRoleDBModel
from .Phone import Phone as PhoneDBModel
from .PhoneType import PhoneType as PhoneTypeDBModel
from .Position import Position as PositionDBModel
from .PreSkill import PreSkill as PreSkillDBModel
from .Role import Role as RoleDBModel
from .RoleSkillBlock import RoleSkillBlock as RoleSkillBlockDBModel
from .Sex import Sex as SexDBModel
from .Skill import Skill as SkillDBModel
from .SkillBlock import SkillBlock as SkillBlockDBModel
from .SkillBlockScore import SkillBlockScore as SkillBlockScoreDBModel
from .SkillBlockSkill import SkillBlockSkill as SkillBlockSkillDBModel
from .SkillGroup import SkillGroup as SkillGroupDBModel
from .SkillGroupSkillBlock import SkillGroupSkillBlock as SkillGroupSkillBlockDBModel
from .SkillScore import SkillScore as SkillScoreDBModel
from .SkillScoreHistory import SkillScoreHistory as SkillScoreHistoryDBModel
from .Status import Status as StatusDBModel
from .Structure import Structure as StructureDBModel